- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ snap }}"
  when: not ansible_check_mode
