package_upgrade: yes
packages:
  - ansible
  - build-essential
  - curl
  - docker-compose
  - docker.io
  - fzf
  - htop
  - jq
  - make
  - wget
  - zip
  - vim
  - xclip

  # GUI
  - chromium-browser

remove_packages:
  - gnome-shell-extension-ubuntu-dock
