- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Download diff-so-fancy
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/opt/diff-so-fancy
    depth: 1

- name: Install tldr with npm
  npm: 
    name: tldr
    global: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install fd with npm
  npm: 
    name: fd-find
    global: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install vscode extensions
  command: code --install-extension "{{ item }}"
  loop: "{{ extensions }}"
