- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Download diff-so-fancy
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/opt/diff-so-fancy
    depth: 1
