- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Download diff-so-fancy
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/opt/diff-so-fancy
    depth: 1

- name: Install tldr with npm
  npm: 
    name: tldr
    global: yes
  become: yes
  become_user: root
  become_method: sudo
  when: not ansible_check_mode

- name: Install vscode extensions
  command: code --install-extension "{{ item }}"
  loop: "{{ extensions }}"

- name: Symlink VSCode keybindings
  file:
    src: "{{ dotfiles_home }}/roles/tools/files/keybindings.json"
    dest: "{{ dotfiles_user_home }}/.config/Code/User/keybindings.json"
    state: link

- name: Symlink VSCode settings
  file:
    src: "{{ dotfiles_home }}/roles/tools/files/settings.json"
    dest: "{{ dotfiles_user_home }}/.config/Code/User/settings.json"
    state: link

- name: Check for .vimrc
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat

- name: Check for badwolf theme
  stat: path="~/opt/badwolf"
  register: badwolf_theme

- name: Download badwolf theme
  git:
    repo: https://github.com/sjl/badwolf.git
    dest: ~/opt/badwolf
    depth: 1
  when: not badwolf_theme.stat.exists

- name: Create .vim/colours directory
  file:
    path: "{{dotfiles_user_home}}/.vim/colors"
    state: directory
    mode: '0755'

- name: Install Badwolf theme
  shell: mv ~/opt/badwolf/colors/*.vim ~/.vim/colors

- name: Back up .vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Vimrc Symlink
  file:
    src: "{{ dotfiles_home }}/roles/tools/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link

