- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Download diff-so-fancy
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: ~/opt/diff-so-fancy
    depth: 1

- name: Install tldr with npm
  npm: 
    name: tldr
    global: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install fd with npm
  npm: 
    name: fd-find
    global: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install vscode extensions
  command: code --install-extension "{{ item }}"
  loop: "{{ extensions }}"

- name: Symlink VSCode keybindings
  file:
    src: "{{ dotfiles_home }}/roles/tools/files/keybindings.json"
    dest: "{{ dotfiles_user_home }}/.config/Code/User/keybindings.json"
    state: link

- name: Symlink VSCode settings
  file:
    src: "{{ dotfiles_home }}/roles/tools/files/settings.json"
    dest: "{{ dotfiles_user_home }}/.config/Code/User/settings.json"
    state: link